channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=25.2
- pip:
  - mlflow==3.5.1
  - defusedxml==0.7.1
  - graphviz==0.21
  - lightgbm==4.6.0
  - matplotlib==3.10.6
  - numpy==1.26.4
  - packaging==25.0
  - pandas==2.1.4
  - psutil==7.0.0
  - pyarrow==22.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.3
name: mlflow-env
